# HTTP Server
[server]
	Address     = ":9279"
	ServerRoot  = "public"
	ServerAgent = "apidoc"
	LogPath     = "./logs/server"

# Logger.
[logger]
    Path        = "./logs"
    Level       = "all"
    Stdout      = true

